version: "3"
services:
  ui:
    image: rsschool/ui:v2
    ports:
      - 8081:8080
  api:
    image: rsschool/api:pg
    ports:
      - 8080:8080
    environment:
      RSSHCOOL_API_MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      RSSHCOOL_API_MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      RSSHCOOL_API_MONGO_CONNECTION_STRING: ${RSSHCOOL_API_MONGO_CONNECTION_STRING}
      RSSHCOOL_API_AUTH_CALLBACK: ${RSSHCOOL_API_AUTH_CALLBACK}
      RSSHCOOL_API_AUTH_CLIENT_ID: ${RSSHCOOL_API_AUTH_CLIENT_ID}
      RSSHCOOL_API_AUTH_CLIENT_SECRET: ${RSSHCOOL_API_AUTH_CLIENT_SECRET}
      RSSHCOOL_API_AUTH_SUCCESS_REDIRECT: ${RSSHCOOL_API_AUTH_SUCCESS_REDIRECT}
      RSSHCOOL_API_SESSION_KEY: ${RSSHCOOL_API_SESSION_KEY}
      RSSHCOOL_API_PG_HOST: ${RSSHCOOL_API_PG_HOST}
      RSSHCOOL_API_PG_USERNAME: ${RSSHCOOL_API_PG_USERNAME}
      RSSHCOOL_API_PG_PASSWORD: ${RSSHCOOL_API_PG_PASSWORD}
      RSSHCOOL_API_PG_DATABASE: ${RSSHCOOL_API_PG_DATABASE}
      RSSHCOOL_API_ADMIN_USERNAME: ${RSSHCOOL_API_ADMIN_USERNAME}
      RSSHCOOL_API_ADMIN_PASSWORD: ${RSSHCOOL_API_ADMIN_PASSWORD}
  proxy:
    image: rsschool/proxy
    ports:
      - 80:8080
    depends_on:
      - api
      - ui
